forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 3000        # 连接超时时间，单位为毫秒
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒
  backend: okhttp3 # 配置后端HTTP API为 okhttp3
  max-retry-count: 0           # 请求失败后重试次数（默认为 0 次不重试）
  
  interceptors:
    - com.alinesno.infra.common.feign.interceptor.GloablInterceptor