server:
  port: 8080 
  
# spring 配置  
spring:
  application:
    name: alinesno-infra-common-simple
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_simple_crm_100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: admin
    password: adminer

sa-token:
  is-print: false