name: 构建和通知

on:
  push:
    branches:
      - main

jobs:
  构建:
    runs-on: ubuntu-latest

    steps:
    - name: 设置 JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: 检出代码
      uses: actions/checkout@v2

    - name: 记录构建开始时间
      id: start-time
      run: echo "::set-output name=start-time::$(date -u +%Y-%m-%dT%H:%M:%SZ)"

    - name: 使用 Maven 构建
      run: mvn clean package

    - name: 记录构建结束时间
      id: end-time
      run: echo "::set-output name=end-time::$(date -u +%Y-%m-%dT%H:%M:%SZ)"

    - name: 发送通知到钉钉
      uses: actionsflow/dingtalk-action@v1
      with:
        webhook: ${{ secrets.DINGTALK_WEBHOOK_URL }}
        message: |
          ${{ github.workflow }} 构建通知
          任务描述：核心框架集成公共和通用的公共包能力，达到核心框架包可拆分可依赖，可集成的目的，通过集成核心框架，形成基础的核心能力。
          构建时间：${{ steps.start-time.outputs.start-time }} ~ ${{ steps.end-time.outputs.end-time }}
          构建时长：$(( $(date -u -d ${{ steps.end-time.outputs.end-time }} +%s) - $(date -u -d ${{ steps.start-time.outputs.start-time }} +%s) )) 秒
          构建状态：${{ job.status }}
          执行人：${{ github.actor }}

