# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Create Nexus Config File
        run: |
          cat << EOF > nexus-config.xml
			<?xml version="1.0" encoding="UTF-8"?>
			<settings>
				<mirrors>
					<mirror>
						<id>mirror</id>
						<mirrorOf>central,jcenter,!rdc-releases,!rdc-snapshots</mirrorOf>
						<name>mirror</name>
						<url>https://maven.aliyun.com/nexus/content/groups/public</url>
					</mirror>

					<mirror>
						<id>rdc-releases</id>
						<mirrorOf>releases</mirrorOf>
						<url>https://packages.aliyun.com/maven/repository/2201346-release-2LoXPn/</url>
					</mirror>
					<mirror>
						<id>rdc-snapshots</id>
						<mirrorOf>snapshots</mirrorOf>
						<url>https://packages.aliyun.com/maven/repository/2201346-snapshot-hFrgM0/</url>
					</mirror>
				</mirrors>

				<servers>
					<server>
						<id>ossrh</id>
						<username>${{ secrets.NEXUS_USERNAME  }}</username>
						<username>${{ secrets.NEXUS_PASSWORD }}</username>
					</server>
					<server>
						<id>rdc-releases</id>
						<username>${{ secrets.NEXUS_USERNAME  }}</username>
						<username>${{ secrets.NEXUS_PASSWORD }}</username>
					</server>
					<server>
						<id>rdc-snapshots</id>
						<username>${{ secrets.NEXUS_USERNAME  }}</username>
						<username>${{ secrets.NEXUS_PASSWORD }}</username>
					</server>
				</servers>
				<profiles>
					<profile>
						<id>rdc</id>
						<properties>
							<altReleaseDeploymentRepository>
								rdc-releases::default::https://packages.aliyun.com/maven/repository/2201346-release-2LoXPn/
							</altReleaseDeploymentRepository>
							<altSnapshotDeploymentRepository>
								rdc-snapshots::default::https://packages.aliyun.com/maven/repository/2201346-snapshot-hFrgM0/
							</altSnapshotDeploymentRepository>
						</properties>
						<repositories>
							<repository>
								<id>central</id>
								<url>https://maven.aliyun.com/nexus/content/groups/public</url>
								<releases>
									<enabled>true</enabled>
								</releases>
								<snapshots>
									<enabled>false</enabled>
								</snapshots>
							</repository>
							<repository>
								<id>snapshots</id>
								<url>https://maven.aliyun.com/nexus/content/groups/public</url>
								<releases>
									<enabled>false</enabled>
								</releases>
								<snapshots>
									<enabled>true</enabled>
								</snapshots>
							</repository>
							<repository>
								<id>rdc-releases</id>
								<url>https://packages.aliyun.com/maven/repository/2201346-release-2LoXPn/</url>
								<releases>
									<enabled>true</enabled>
								</releases>
								<snapshots>
									<enabled>false</enabled>
								</snapshots>
							</repository>
							<repository>
								<id>rdc-snapshots</id>
								<url>https://packages.aliyun.com/maven/repository/2201346-snapshot-hFrgM0/</url>
								<releases>
									<enabled>false</enabled>
								</releases>
								<snapshots>
									<enabled>true</enabled>
								</snapshots>
							</repository>
						</repositories>
						<pluginRepositories>
							<pluginRepository>
								<id>central</id>
								<url>https://maven.aliyun.com/nexus/content/groups/public</url>
								<releases>
									<enabled>true</enabled>
								</releases>
								<snapshots>
									<enabled>false</enabled>
								</snapshots>
							</pluginRepository>
							<pluginRepository>
								<id>snapshots</id>
								<url>https://maven.aliyun.com/nexus/content/groups/public</url>
								<releases>
									<enabled>false</enabled>
								</releases>
								<snapshots>
									<enabled>true</enabled>
								</snapshots>
							</pluginRepository>
							<pluginRepository>
								<id>rdc-releases</id>
								<url>https://packages.aliyun.com/maven/repository/2201346-release-2LoXPn/</url>
								<releases>
									<enabled>true</enabled>
								</releases>
								<snapshots>
									<enabled>false</enabled>
								</snapshots>
							</pluginRepository>
							<pluginRepository>
								<id>rdc-snapshots</id>
								<url>https://packages.aliyun.com/maven/repository/2201346-snapshot-hFrgM0/</url>
								<releases>
									<enabled>false</enabled>
								</releases>
								<snapshots>
									<enabled>true</enabled>
								</snapshots>
							</pluginRepository>
						</pluginRepositories>
					</profile>
				</profiles>
				<activeProfiles>
					<activeProfile>rdc</activeProfile>
				</activeProfiles>
			</settings>
			EOF

      - name: Build with Maven
        run: mvn -B clean deploy --settings nexus-config.xml

      - name: Build and Deploy to Nexus
        run: mvn clean deploy --settings nexus-config.xml
